-- ============================================================================
-- HRMS Sequences
-- Surrogate key generators for all tables
-- NOTE: Uses simple incrementing sequences (no UUID/GUID)
-- This is typical for Oracle Forms applications of this era
-- ============================================================================

-- Core Employee sequences
CREATE SEQUENCE HRMS.SEQ_DEPARTMENT START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_LOCATION START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_JOB_GRADE START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_JOB_TITLE START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_EMPLOYEE START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_EMP_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_DEPENDENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_EMERGENCY_CONTACT START WITH 1 INCREMENT BY 1 NOCACHE;

-- Employee number sequence (used to generate EMP-XXXXXX format)
-- BUG: NOCACHE means gaps in sequence, but generate_emp_number in
-- PKG_EMPLOYEE uses MAX()+1 instead, creating a race condition
CREATE SEQUENCE HRMS.SEQ_EMP_NUMBER START WITH 1000 INCREMENT BY 1 NOCACHE;

-- Payroll sequences
CREATE SEQUENCE HRMS.SEQ_SALARY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PAY_ELEMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_EMP_PAY_ELEMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PAY_PERIOD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PAYROLL_RUN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PAYROLL_DETAIL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_TAX_BRACKET START WITH 1 INCREMENT BY 1 NOCACHE;

-- Leave sequences
CREATE SEQUENCE HRMS.SEQ_LEAVE_TYPE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_LEAVE_BALANCE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_LEAVE_REQUEST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_LEAVE_ACCRUAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_HOLIDAY START WITH 1 INCREMENT BY 1 NOCACHE;

-- Performance sequences
CREATE SEQUENCE HRMS.SEQ_REVIEW_CYCLE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PERF_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_PERF_GOAL START WITH 1 INCREMENT BY 1 NOCACHE;

-- System sequences
CREATE SEQUENCE HRMS.SEQ_AUDIT START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE HRMS.SEQ_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_USER_SESSION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_SYSTEM_PARAM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HRMS.SEQ_LOOKUP START WITH 1 INCREMENT BY 1 NOCACHE;
